jobs:
  - job: Build_Lil_Debi
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: sudo apt-get update
    - script: sudo apt-get install autoconf automake libtool transfig wget patch texinfo ant make openjdk-8-jdk faketime
    - script: wget https://dl.google.com/android/repository/android-ndk-r19-linux-x86_64.zip
    - script: wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
    - script: unzip android-ndk-r19-linux-x86_64.zip
    - script: unzip sdk-tools-linux-4333796.zip
    - script: export NDK_BASE=./android-ndk-r19
    - script: export NDK_PLATFORM_LEVEL=23
    - script: export NDK_ABI=arm
    - script: export NDK_COMPILER_VERSION=4.6
    - script: exxport HOST=x86
    - script: make -C external assets
    - script: ./setup-ant
    - script: ant debug
      